In [8]:
#Guess the type
type('hi')

#Type conversion
"I said" + (" Hey "*2) + " Hey"

'I said Hey  Hey  Hey'

In [17]:
#Slicing
x = ["a", "b", "c", "d"]
x[1] # b
x[-1] # negative slicing도 가능. 인덱싱 주의, d

x[1]+x[-1] #bd

x[1:3] #['b', 'c']

['b', 'c']

In [36]:
x = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

x[4:-1] #[40,50, 60, 70, 80] 맨 뒤에는 포함하지 않으니 -2까지 읽으니까!

x[2:8:3] #[20,50] 2부터 7까지 4씩 증가

x[:7] # 인덱스 처음부터 6까지

x[7:] # 7부터 끝까지

x[:] # 전체

x[:7:2] # [0, 20, 40, 60]

x[7::2] # [70, 90]

x[::2] # [0, 20, 40, 60, 80 

x[::] # 전체. x[:]와 동일

x[5:1:-1] # 5부터 2까지. [50, 40, 30, 20]
x[:5:-1]  # [90, 80, 70, 60]
# 주의사항. 마이너스일 경우 시작 인덱스가 더 커야 한다. 

# 만약 시작 인덱스가 더 작다면?
x[3:7:-1] # [] 나옴

x[::-1] # [90, ...., 0]

# len 응용
x[0:len(x)] # [0, 10, ..... , 90]
x[:len(x)]

x[:6] + x[-4:] # 전체 다
x[:6] # [0, 10, .... 50]
x[-4:] # [60, 70, 80, 90]



[60, 70, 80, 90]

In [38]:
# Subsetting lists of lists
x = [["a", "b", "c"], ["d", "e", "f"], ["g", "h", "i"]]
x[2][0] # 'g'
x[2][:2] # ['g', 'h']

['g', 'h']

In [45]:
x = ["a", "b", "c"]
# y = x
# y[1] = "z"
y # ['a', 'z', 'c']
x # ['a', 'z', 'c'] 
# x,y는 실제 값 자체가 아니라 목록에 대한 참조를 복사하므로 모두 업데이트된 것을 볼 수 있음 

# 메모리의 새 목록을 가리키는 y를 만들고 싶다면, 등호(=)가 아닌 방법을 사용해야 함
y = x[:]
y[1] = 'z'
x # ['a', 'b', 'c']
y # ['a', 'z', 'c']
    

['a', 'z', 'c']

In [47]:
x = ['a', 'b', 'c', 'd']
x[1] = 'r'
x[2:] = ['s', 't']
x # ['a', 'r', 's', 't']

['a', 'r', 's', 't']

In [48]:
x = ['a', 'b', 'c', 'd']
y = x + ['e', 'f']
y # ['a', 'b', 'c', 'd', 'e', 'f']

['a', 'b', 'c', 'd', 'e', 'f']

In [52]:
x = ['a', 'b', 'c', 'd']
# del(x[1]) # 메모리 낭비 없이 지워줌
x # ['a', 'c', 'd']

del(x[-3:-1])
x # ['a', 'd'] # 위에 del()은 주석처리했을 때의 결과임

['a', 'd']

In [53]:
result = type(3.0)
result # float

float

In [58]:
help(max)
help(sorted) # return a 'new' list

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [63]:
full = [1, 3, 7, 14]
x = sorted(full)
x # [1,3, 7, 14]

y = sorted(full, reverse=True)
y # [14, 7, 3, 1]

[1, 3, 7, 14]

In [92]:
# Methods
sister = 'liz'
sister.replace('z', 'sa') # 'lisa cf) sister 출력하면 'liz' 나옴

sister.upper() #'LIZ'
sister.count('s') # 0 여기서 헷갈리면 안되는게 sister의 count를 세는게 아님. "객체.count()인 것"
sister.count('l') # 1 

place = "New York"
place.upper() #'NEW YORK'
place.count('n') # 0
place.count('N') # 1

areas = [11.25, 18.0, 12.0, 10.75, 9.50]
areas.index(11.25) # 0
areas.count(9.50) # 1 

areas = [1, 2, 3, 4]
areas.append(5)
areas # [1, 2, 3, 4, 5]

areas.reverse()
areas # [5, 4, 3, 2, 1]
print(areas.reverse()) # None. .reverse()는 객체에 대한 메소드. '이 메소드'의 리턴값은 None


None


[1, 1, 2, 3, 4]

In [94]:
import numpy 
numpy.array([1,2,3]) # array([1,2,3])

# 딱 한 기능을 가지고 올 때
from numpy import array
array([1,2,3]) # array([1,2,3]) 

# 하지만 코드가 길어지면 import 한 걸 잊을 수도 있기 때문에 그냥 numpy 전체를 import 해서 사용해주는게 선호됨

array([1, 2, 3])

In [99]:
import math

r = 0.43

C = 2*math.pi*r
C # 2*r만 한 것과는 다름! 

A = math.pi **2
A

9.869604401089358

In [101]:
import math
from math import pi 

from math import radians

dist = r*radians(12) # math.radians가 아니라 바로 썼다는게 포인트

0.43

In [104]:
import numpy as np

height = [1,2,3,4,5]
np_height = np.array(height)
np_height # array([1,2,3,4,5])

weight = [10, 20, 30, 40, 50]
np_weight = np.array(weight)
np_weight # array([10, 20, 30, 40, 50])

bmi = np_weight/np_height**2
bmi # array([10, 5, 3.333, 2.5, 2])

# point는 오류없이 잘 수행된다는 것. 일반 파이썬이었으면 오류 

# 일반 파이썬에서 오류가 나는 이유 
# ㄴ 우리가 원하는 것과 같은 목록으로 계산을 수행하지 않기 때문. 반면 numpy는 지혜롭게 계산을 해줌

array([10.        ,  5.        ,  3.33333333,  2.5       ,  2.        ])

In [ ]:
# Numpy array : contain only one type
# ㄴ numpy가 빠를 수 있는 이유는 한 타입만 넣을 수 있는 특징 때문

# Numpy 배열은 새로운 종류다.
# ㄴ type() 찍어봐도 다름. 

In [107]:
python_list = [1,2,3]
numpy_array = np.array([1,2,3])
numpy_array # array([1, 2, 3])

python_list + python_list # [1,2,3,1,2,3]
numpy_array + numpy_array # array([2,4,6])

# different type, different behavior! 

array([2, 4, 6])

In [114]:
bmi = [1,2,3,4,5]
bmi[1] #2

# bmi>3 # 지금 당장은 에러 

height = [1,2,3,4,5]
np_height = np.array(height)
np_height # array([1,2,3,4,5])

weight = [10, 20, 30, 40, 50]
np_weight = np.array(weight)
np_weight # array([10, 20, 30, 40, 50])

bmi = np_weight/np_height**2
bmi # array([10, 5, 3.333, 2.5, 2])

bmi > 3 # array([True, True, True, False, False])

#대괄호 안에 이 bool 배열을 이용해서 subsetting이 가능
bmi[bmi>5] # arrat(10.)

# 비교 결과를 사용하여 데이터를 선택하는 것은 놀라운 통찰력을 얻는 매우 일반적인 방법임 


array([10.])

In [116]:
baseball = [1,2,3,4,5]
np_baseball = np.array(baseball)
np_baseball # array([1,2,3,4,5])

print(type(np_baseball)) # <class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [119]:
height_in = [74, 74, 72, 75]
np_height = np.array(height_in)
np_height # array([74, 74, 72, 75])

print(np_height) # [74 74 72 75]

np_height_m = np_height * 0.0254
print(np_height_m)

[74 74 72 75]
[1.8796 1.8796 1.8288 1.905 ]


In [120]:
a = [1]
b = a*5
b # [1,1,1,1,1]

[1, 1, 1, 1, 1]

In [3]:
height_in = [74, 74, 72, 75]
weight = [10, 20, 30, 40]

np_height_m = np.array(height_in)*0.0254
np_weight_kg = np.array(weight)*0.453592
bmi = np_weight_kg/np_height_m**2
bmi

NameError: name 'np' is not defined

In [2]:
# boolean numpy arrays
# high = y>5
# high

light = bmi < 21
light  # array([ True,  True,  True,  True])

bmi[light]

NameError: name 'bmi' is not defined

In [4]:
import numpy as np

np.array([True, 1, 2]) + np.array([3,4,False])
# array([4, 5, 2])

array([4, 5, 2])